# .github/workflows/portfolio-deploy-trigger.yml
name: Triggered by Netlify Deploy

on:
  repository_dispatch:
    types: [netlify-deploy-success]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run Tests with Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -ac &
          mvn clean test -B

      - name: Notify Portfolio is Live
        run: echo "✅ Netlify deployed. Tests run triggered."

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/surefire-reports
